# Generated by Django 5.0.1 on 2024-02-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('D', 'Drip'), ('P', 'Pipe'), ('F', 'Fitting'), ('T', 'Tissue')], max_length=2),
        ),
    ]
